name: ET_reminder

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # run once a day
#  schedule:
#    - cron: '15 17 * * 2'

jobs:
  update-repo:
    runs-on: ubuntu-latest
    name: Update repository
    steps:
      - name: install python
        run: |
          apt-get update
          apt-get install -y python3
      - name: Running ET_reminder.py
        shell: bash
        run: python3 ./.github/workflows/ET_reminder.py
